name: merged

on:
  push:
    branches:
      - "main"

permissions:
  issues: write
  actions: write
  contents: write
  packages: write
  pull-requests: write
  repository-projects: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: "Australia/Sydney"
  LANG: "en_AU.UTF-8"

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'chore(release)')
    steps:
      - run: |
          echo ${{ toJson(github.event) }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
