name: pr

on:
  schedule:
    - cron: "0 20 * * 0" # Sunday 8pm UTC -> Monday 7am (Australian Eastern Daylight Time)
    # - cron: "0 20 * * 0" # Sunday 8pm UTC -> Monday 7am (Australian Eastern Daylight Time)
  workflow_dispatch:

permissions:
  checks: write
  actions: write
  contents: write
  packages: write
  statuses: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: "Australia/Sydney"
  LANG: "en_AU.UTF-8"
  GITHUB_TOKEN: ${{ github.token }}
  RELEASE_BRANCH: "chore/create-release"

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: meta
        id: meta
        shell: bash
        run: |
          echo "package_version=$(date +'%-y.%-m.%-d-alpha.%-H%-M%-S')" >> "$GITHUB_OUTPUT"

      - name: create commit
        shell: bash
        run: |
          echo "Setting user data..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b "$RELEASE_BRANCH"
          echo "Latest stable version: $NPM_PACKAGE_VERSION" > .version
          git add .
          git status
          git commit -a -m "chore(release): version $NPM_PACKAGE_VERSION"
          git status
          git push origin "$RELEASE_BRANCH" --force-with-lease
        env:
          NPM_PACKAGE_VERSION: ${{ steps.meta.outputs.package_version }}

      - name: create pull request
        shell: bash
        run: |
          pull_request_title="chore(release): version $NPM_PACKAGE_VERSION"
          pull_request_url=$(gh pr create --base main --head "$RELEASE_BRANCH" --title "$pull_request_title" --body "This PR is auto-generated by Github actions")
          echo "Pull request: ${pull_request_url}"
          gh pr merge --auto --squash --delete-branch "$pull_request_url"
        env:
          NPM_PACKAGE_VERSION: ${{ steps.meta.outputs.package_version }}
