name: pr

on:
  schedule:
    - cron: "0 20 * * 0" # Sunday 8pm UTC -> Monday 7am (Australian Eastern Daylight Time)
    # - cron: "0 20 * * 0" # Sunday 8pm UTC -> Monday 7am (Australian Eastern Daylight Time)
  workflow_dispatch:

permissions:
  checks: write
  actions: write
  contents: write
  packages: write
  statuses: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: "Australia/Sydney"
  LANG: "en_AU.UTF-8"

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: create commit
        shell: bash
        run: |
          branch="chore/create-release"
          package_version=$(date +'%-y.%-m.%-d')

          echo "Setting user data..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout -b "$branch"

          echo "Latest stable version: $package_version" > .version

          git add .
          git status

          git commit -a -m "chore(release): version $package_version"
          git status

          git push origin "$branch" --force-with-lease

      - name: create pull request
        shell: bash
        run: |
          package_version=$(date +'%-y.%-m.%-d')
          # echo "package_version=v$(date +'%-y.%-m.%-d')" >> "$GITHUB_OUTPUT"
          branch="chore/create-release"

          pull_request_title="chore(release): version $package_version"
          pull_request_url=$(gh pr create --base main --head "$branch" --title "$pull_request_title" --body "This PR is auto-generated by Github actions")

          echo "Pull request: ${pull_request_url}"
          gh pr merge --auto --squash --delete-branch "$pull_request_url"
